pgdata:
  image: postgres:9.3
  volumes:
    - /var/lib/postgresql/data
  command: true

postgres:
  image: postgres:9.3
  volumes_from:
    - pgdata
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password

pentahodata:
  image: java:7
  volumes:
    - /pentaho-data
  command: true

pentaho:
  image: leandrocp/pentaho-server
  volumes_from:
    - pentahodata
  links:
    - postgres:postgres
  ports:
    - "8080:8080"
  environment:
    DB_USER: postgres
    DB_PASS: password
